name: codefinger
description:
meta_description: "Deploying with JRuby, Healthy Programmer, Remote Pairing, Heroku"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jkutner.github.io'
google_analytics: 'UA-60067944-1'

# Details for the RSS feed generator
url:            'http://jkutner.github.io'
author:         'Joe Kutner'

gems: [jekyll-paginate]