name: codefinger
description: blog
meta_description: "Cloud Native Buildpacks, Healthy Programmer, Salesforce, Heroku"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jkutner.github.io'
google_analytics: 'UA-60067944-1'

# Details for the RSS feed generator
url:            'http://jkutner.github.io'
author:         'Joe Kutner'

gems: [jekyll-paginate]
